# -*- coding: utf-8 -*-
"""Experiment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lLUEcsM8UJ5TTW3zZA1-knrsvLQz_6HU
"""

a=10
b=20
add=a+b
print("Adition =",add)